# Generated by Django 2.2.10 on 2020-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
