# Generated by Django 2.2.10 on 2020-06-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(),
        ),
    ]
